# Use postgres/example user/password credentials
version: '3.1'

services:
  momentum-test-backend:
    build: .
    restart: unless-stopped
    ports:
      - 3001:80
    environment:
      EMAIL_ADDRESS: test@example.com
      EMAIL_PASSWORD: test
      EMAIL_HOST: smtp.example.com
      DATABASE_USE_POSTGRESQL: "false"
      VIDEO_PATH: videos
      ALLOWED_ORIGINS: http://localhost
      ALLOWED_HOSTS: 127.0.0.1,localhost