# Use postgres/example user/password credentials
version: '3.1'

services:
  momentum-db:
    image: postgres
    restart: unless-stopped
    container_name: momentum-db
    environment:
      POSTGRES_USER: momentum
      POSTGRES_PASSWORD: momentum # this should be changed for security
      POSTGRES_DB: momentum

  momentum-backend:
    build: ..
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - momentum-db
    environment:
      EMAIL_ADDRESS: test@example.com
      EMAIL_PASSWORD: test
      EMAIL_HOST: smtp.example.com
      DATABASE_NAME: momentum
      DATABASE_USER: momentum
      DATABASE_PASSWORD: momentum
      DATABASE_HOST: momentum-db  # this needs to be the container name of the db
      DATABASE_PORT: 5432
      VIDEO_PATH: videos
      ALLOWED_ORIGINS: http://localhost
      ALLOWED_HOSTS: 127.0.0.1,localhost
      WEBSITE_URL: localhost:8080