name: Deploy Testserver

on: workflow_dispatch

env:
  PYTHON_VERSION: 3.8

jobs:
  test-test-server:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./BPBackendDjango/requirements.txt
      - name: Makemigrations
        run: python ./BPBackendDjango/manage.py makemigrations
      - name: Migrate
        run: python ./BPBackendDjango/manage.py migrate
      - name: Test
        run: python ./BPBackendDjango/manage.py test BPBackendDjango/ --noinput

  deploy-test-server:
    runs-on: self-hosted
    needs: test-test-server
    steps:
      - run: rm -rf /home/github/bachelor-praktikum/api/test-server/*
        name: Delete old files
      - run: cp -r BPBackendDjango/* /home/github/bachelor-praktikum/api/test-server/
        name: Copy files
      - run: sudo /usr/bin/systemctl restart bp-test-backend.service
        name: Restarting Testserver
