name: Deploy

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.8
  EMAIL_ADDRESS: test@example.com
  EMAIL_PASSWORD: test
  EMAIL_HOST: smtp.example.com
  DATABASE_USE_POSTGRESQL: false
  VIDEO_PATH: videos
  ALLOWED_ORIGINS: http://localhost
  ALLOWED_HOSTS: http://localhost
  AI_URL: http://localhost

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Test
        run: python ./manage.py test --noinput

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/bp-momentum/backend:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

