name: Test

on:
  push:
    branches:
      - '**'
      - '!main'

env:
  PYTHON_VERSION: 3.8

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./BPBackendDjango/requirements.txt
      - name: Copy config
        run: cp /home/github/bachelor-praktikum/api/store/test-settings.json ./settings.json
      - name: Test
        run: python ./BPBackendDjango/manage.py test BPBackendDjango/ --noinput
